
      
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  deploy:                                         # a free machine-readable name for this job
    runs-on: ubuntu-latest                        # specify the base operating system
    container:
        image: leopoul/markmap:1.0.0
        options: -v  /__w/testing_markmap/testing_markmap/markdown/:/app
    steps:
      - name: Checkout repo content               # fetch the contents of the repository
        uses: actions/checkout@v2
      - name: Prepare build environment
        run: pwd && ls -al /app
      - name: Deploy on github pages              # Use a third-party plugin to upload the content
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: build
